[[inputs.ping]]
  urls = ["<url 1>", "<url 2>"]
  count = 5            # Send 5 pings per interval
  ping_interval = 0.2  # Wait 200ms between those 5 pings
  timeout = 1.0        # How long to wait for each individual response
  method = "native"

[[processors.enum]]
  namepass = ["ping"]
  [[processors.enum.mapping]]
    tag = "url"
    dest = "alias"
    [processors.enum.mapping.value_mappings]
      "<url 1>" = "DNS 1"
      "<url 2>" = "DNS 2"

[[inputs.smartctl]]
  path = "/usr/local/sbin/smartctl"
  devices_include = [ "/dev/nvme0" ]

[[inputs.haproxy]]
  servers = ["http://127.0.0.1:2200/haproxy/haproxy_stats.php?haproxystats=1"]

  ## The fieldpass array tells Telegraf to drop ALL HAProxy metrics
  ## EXCEPT for the exact ones listed here.
  fieldpass = [
    "bin",
    "bout",
    "scur",
    "ereq",
    "eresp",
    "http_response.2xx",
    "http_response.4xx",
    "http_response.5xx",
    "check_duration",
    "status"
  ]

[[inputs.ntpq]]
  ## Use -p to list peers and -n to keep it numeric (no DNS)
  options = "-p -n"

[[inputs.x509_cert]]
  sources = ["/conf/acme/<cert>.crt"]
  tls_ca = "/conf/acme/<ca>.ca"

[[inputs.exec]]
  commands = [
    "/usr/local/bin/telegraf_gateway_status.sh",
    "/usr/local/bin/telegraf_net_if.sh",
    "/usr/local/bin/telegraf_node_uname.sh",
    "/usr/local/bin/telegraf_node_temp.sh",
    "/usr/local/bin/telegraf_pfsense_services.sh",
    "/usr/local/bin/telegraf_node_netstat_mbuf.sh",
    "/usr/local/bin/telegraf_wireguard.sh",
    "/usr/local/bin/telegraf_tailscale.sh"
  ]
  timeout = "30s"
  data_format = "influx"

  ## If the "interface" tag matches any of these strings, drop the metric entirely.
  [inputs.exec.tagdrop]
    interface = [ "<interface name>"]

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2

  ## Explicitly define Prometheus metric types using the final metric names.
  ## Glob patterns (*) are fully supported.
  [outputs.prometheus_client.metric_types]
    gauge = [
      # Packet Filter Gauges
      "pf_entries",

      # Gateway Status Gauges
      "gateway_rtt_milliseconds",
      "gateway_loss_ratio",
      "gateway_rttsd_milliseconds",

      # Network Interface Gauges
      "net_if_info",
      "net_if_admin_state",
      "net_if_link_state",

      # Netstad Gauges
      "netstat_tcp_*",
      "netstat_udp_*",

      # Node Temperature Gauges
      "node_temp_celsius",

      # Node Uname Gauges
      "node_uname_info",

      # Node Netstat Mbuf Gauges
      "node_netstat_mbuf_*",

      # PfSense Service Status Gauges
      "pfsense_service_status",

      # WireGuard Gauges
      "wireguard_peer_latest_handshake_seconds",

      # Tailscale Gauges
      "tailscale_backend_state",

      # Ping Gauges
      "ping_average_response_ms",
      "ping_maximum_response_ms",
      "ping_minimum_response_ms",
      "ping_standard_deviation_ms",
      "ping_percent_packet_loss",
      "ping_result_code",
      "ping_ttl",

      # SMART Gauges
      "smartctl_health_ok",
      "smartctl_percentage_used",
      "smartctl_temperature",
      "smartctl_critical_warning",
      "smartctl_available_spare",
      "smartctl_available_spare_threshold",
      "smartctl_capacity",
      "smartctl_logical_block_size",

      # HAProxy Gauges
      "haproxy_scur",
      "haproxy_check_duration",

      # NTPQ Gauges
      "ntpq_*",

      # X509 Certificate Gauges
      "x509_cert_*"
    ]

    # Counters represent cumulative metrics that only ever go up (or reset to 0).
    # Useful if you add metrics later like total bytes or total errors.
    counter = [
      # Packet Filter Counters
      "pf_searches",
      "pf_inserts",
      "pf_removals",
      "pf_match",
      "pf_state_mismatch",
      "pf_fragment",
      "pf_normalize",
      "pf_bad_offset",
      "pf_bad_timestamp",
      "pf_short",
      "pf_proto_cksum",
      "pf_ip_option",
      "pf_memory",
      "pf_state_limit",
      "pf_src_limit",
      "pf_congestion",
      "pf_state_insert",
      "pf_synproxy",

      # Network Interface Counters
      "*_bytes_received",
      "*_bytes_transmitted",

      # Total and Error Counters
      "*_total",
      "*_errors",

      # Ping Counters
      "ping_packets_*",

      # SMART Counters
      "smartctl_media_errors",
      "smartctl_data_units_written",
      "smartctl_power_cycles",
      "smartctl_unsafe_shutdowns",
      "smartctl_controller_busy_time",
      "smartctl_critical_comp_time",
      "smartctl_data_units_read",
      "smartctl_host_reads",
      "smartctl_host_writes",
      "smartctl_num_err_log_entries",
      "smartctl_power_on_hours",
      "smartctl_warning_temp_time",

      # HAProxy Counters
      "haproxy_bin",
      "haproxy_bout",
      "haproxy_ereq",
      "haproxy_eresp",
      "haproxy_http_response_*"
    ]
